project:
  type: website
  title: "Big Data and Analytics"
  output-dir: _site 
  post-render: "bash scripts/decktape.sh"
format:
  revealjs:
    theme: simple
    width: 1600
    height: 900
    lazy-load: true
    slide-number: true
    include-before-body: assets/header.html
    css: [assets/frankfurt.css]
    auto-stretch: false
    slide-level: 2
