project:
  title: "My Slides"
  output-dir: _site 
format:
  revealjs:
    theme: simple
    width: 1600
    height: 900
    lazy-load: true
    slide-number: true
    include-before-body: assets/header.html
    css: [assets/frankfurt.css]
    auto-stretch: false
